### PR TITLE
Fixed #594

### LINKED ISSUE #594: Patterns in signatures
The following program
```rust
#[logic]
fn test((x, y): (u32, u32)) -> u32 {
    x
}

#[ensures(result == x)]
fn test2((x, y): (u32, u32)) -> u32 {
    x
}
```
produces the following why3 file
```
module CreusotExperiments_Fail_Test_Stub
  use mach.int.Int
  use mach.int.UInt32
  function test (_1' : (uint32, uint32)) : uint32
end
module CreusotExperiments_Fail_Test_Interface
  use mach.int.Int
  use mach.int.UInt32
  function test (_1' : (uint32, uint32)) : uint32
end
module CreusotExperiments_Fail_Test
  use mach.int.Int
  use mach.int.UInt32
  function test [#"../src\fail.rs" 4 0 4 34] (_1' : (uint32, uint32)) : uint32 =
    [#"../src\fail.rs" 5 4 5 5] x
  val test (_1' : (uint32, uint32)) : uint32
    ensures { result = test _1' }
    
end
module CreusotContracts_Logic_Resolve_Resolve_Resolve_Stub
  type self
  predicate resolve (self : self)
end
module CreusotContracts_Logic_Resolve_Resolve_Resolve_Interface
  type self
  predicate resolve (self : self)
end
module CreusotContracts_Logic_Resolve_Resolve_Resolve
  type self
  predicate resolve (self : self)
  val resolve (self : self) : bool
    ensures { result = resolve self }
    
end
module CreusotContracts_Logic_Resolve_Impl0_Resolve_Stub
  type t1
  type t2
  predicate resolve (self : (t1, t2))
end
module CreusotContracts_Logic_Resolve_Impl0_Resolve_Interface
  type t1
  type t2
  predicate resolve (self : (t1, t2))
end
module CreusotContracts_Logic_Resolve_Impl0_Resolve
  type t1
  type t2
  clone CreusotContracts_Logic_Resolve_Resolve_Resolve_Stub as Resolve1 with type self = t2
  clone CreusotContracts_Logic_Resolve_Resolve_Resolve_Stub as Resolve0 with type self = t1
  predicate resolve (self : (t1, t2)) =
    Resolve0.resolve (let (a, _) = self in a) /\ Resolve1.resolve (let (_, a) = self in a)
  val resolve (self : (t1, t2)) : bool
    ensures { result = resolve self }
    
end
module CreusotContracts_Logic_Resolve_Impl2_Resolve_Stub
  type t
  predicate resolve (self : t)
end
module CreusotContracts_Logic_Resolve_Impl2_Resolve_Interface
  type t
  predicate resolve (self : t)
end
module CreusotContracts_Logic_Resolve_Impl2_Resolve
  type t
  predicate resolve (self : t) =
    true
  val resolve (self : t) : bool
    ensures { result = resolve self }
    
end
module CreusotExperiments_Fail_Test2_Interface
  use mach.int.Int
  use mach.int.UInt32
  val test2 [@cfg:stackify] (_1' : (uint32, uint32)) : uint32
    ensures { [#"../src\fail.rs" 8 10 8 21] result = x }
    
end
module CreusotExperiments_Fail_Test2
  use mach.int.Int
  use mach.int.UInt32
  clone CreusotContracts_Logic_Resolve_Impl2_Resolve as Resolve1 with type t = uint32
  clone CreusotContracts_Logic_Resolve_Impl0_Resolve as Resolve0 with type t1 = uint32, type t2 = uint32,
    predicate Resolve0.resolve = Resolve1.resolve, predicate Resolve1.resolve = Resolve1.resolve
  let rec cfg test2 [@cfg:stackify] [#"../src\fail.rs" 9 0 9 35] (_1' : (uint32, uint32)) : uint32
    ensures { [#"../src\fail.rs" 8 10 8 21] result = x }
    
   = [@vc:do_not_keep_trace] [@vc:sp]
  var _0 : uint32;
  var _1 : (uint32, uint32);
  var x_2 : uint32;
  var y_3 : uint32;
  {
    _1 <- _1';
    goto BB0
  }
  BB0 {
    x_2 <- (let (a, _) = _1 in a);
    y_3 <- (let (_, a) = _1 in a);
    assume { Resolve0.resolve _1 };
    _0 <- x_2;
    return _0
  }
  
end
```
Note that `x` is being used in `test2`s specs and `test`s body even though it is never bound.

It might be possible to modify [`pearlite`](https://github.com/xldenis/creusot/blob/master/creusot/src/translation/pearlite.rs#:~:text=pub(crate)%20fn%20pearlite(tcx%3A%20TyCtxt%2C%20id%3A%20LocalDefId)%20%2D%3E%20CreusotResult%3CTerm%3E) to additional let bindings to handle arguments using patterns, but I can't seem to find where the '_1 symbol comes from.

### PR DESCRIPTION
**Pull request by dewert99**
Fixes #594.

Note issue #605 leads to issue when pattern matching with a struct and needs to be fixed seperatly

### CODE REVIEW

File: creusot/src/translation/pearlite.rs [hunk 1]
```diff
@@ -164,6 +164,35 @@ struct ThirTerm<'a, 'tcx> {
 // TODO: Ensure that types are correct during this translation, in particular
 // - Box, & and &mut
 impl<'a, 'tcx> ThirTerm<'a, 'tcx> {
+    fn body_term(&self, expr: ExprId) -> CreusotResult<Term<'tcx>> {
+        let body = self.expr_term(expr)?;
+        let owner_id = util::closure_owner(self.tcx, self.item_id.into());
```
Comment (xldenis) [inline creusot/src/translation/pearlite.rs:169]: I'm a worried this won't play well with Pearlite closures, where we wouldn't want to look at the closure owner for params but the closure itself.

Comment (xldenis) [reply creusot/src/translation/pearlite.rs:169]: Additionnally, what about when we are looking at the contracts of a program closure?

File: creusot/src/util.rs [hunk 2]
```diff
@@ -678,3 +682,11 @@ pub(crate) fn closure_capture_subst<'tcx>(
     let TyKind::Closure(_, substs) = tcx.type_of(def_id).kind() else { unreachable!() };
     ClosureSubst { self_, map: subst, post: is_post, def_id, bound: Default::default(), substs }
 }
+
+pub(crate) struct AnonymousParamName(pub(crate) usize);
+
+impl Display for AnonymousParamName {
```
Comment (xldenis) [inline creusot/src/util.rs:688]: :+1:

File: creusot/src/translation/pearlite.rs (hunk 1 above)
Comment (xldenis) [reply creusot/src/translation/pearlite.rs:169]: Perhaps, we could make `ensures` and `requires` duplicate the parent's signature in the generated closure so we don't need to look at the parents to extract the params?

Comment (dewert99) [reply creusot/src/translation/pearlite.rs:169]: My first thought would be to get the parent if the def_id had the attribute `#[creusot::decl::spec]`, but looking at the macro expansion it seems like the specs on closures are siblings of the closure, not children.  Given an arbitrary spec_closure, it also looks like there is no good way to tell if it specifies the outer function or a different closure so I would know whether or not to use the parent.

Comment (dewert99) [reply creusot/src/translation/pearlite.rs:169]: I'd prefer not to touch creusot_contracts_proc, but that doesn't seem possible.  I'm trying to decide if it would be better to duplicate the arguments as you suggested or go in the other direction and push spec_closures into the closures they specify and remove their arguments as well.  If we did that would it be possible to do away with IDs (`#[creusot::item]`) since all specifications would be directly contained in the thing they specify?

Comment (dewert99) [reply creusot/src/translation/pearlite.rs:169]: I noticed you were using `dummy_call` and `closure_result` to help with type inference, if the spec_closure no longer repeats the arguments `dummy_call` won't be needed.  We can also modify the closure being specified to call `pub fn closure_result<R, F: FnOnce(R) -> bool>(_: F, _: R)` with it's ensures clause and return value instead of doing it in the spec closure.  Is there any other reason why this approach wouldn't work?

Comment (xldenis) [reply creusot/src/translation/pearlite.rs:169]: >  go in the other direction and push spec_closures into the closures they specify and remove their arguments as well

I think the reason I did it that way is that we break type inference otherwise. We want to let real closure guide inference as much as possible. A possibly a little crazy idea I just had was: push the spec_closures in the program closure but put it at the *end* of the program closure, so hopefully type inference infers the arg types before getting to the specification.

Comment (dewert99) [reply creusot/src/translation/pearlite.rs:169]: I is sort of what I was thinking for the `return` arg.  I was wondering if we could do away with the other args all together like we do with top level specs.

**Comment by dewert99** [comment]
I tried modifying `creusot_contracts` so that specs on closures a specified within the closure, and everything in the test suite seems to type check, but the mlcfg output is different (which makes sense since things are encoded differently), do you think you could check this over?

**Comment by xldenis** [comment]
> I tried modifying creusot_contracts so that specs on closures a specified within the closure, and everything in the test suite seems to type check, but the mlcfg output is different (which makes sense since things are encoded differently), do you think you could check this over?

I'll do that now.

**Comment by xldenis** [comment]
It all looks good, a manual read of the MLCFG shows to me that only shuffling of instructions and temporary variables occured. Moreover, the only foreseeable side-effect of a bug would be that contracts are dropped (leading to verification errors) or inference is impacted (leading to failing to typecheck).

**Comment by xldenis** [comment]
Go ahead and update the MLCFG files & the few affected sessions.

**Comment by dewert99** [comment]
Now that I switched the closure spec nesting I was able to use the strategy to use the parent `defid` for `#[creusot::decl::spec]` and the original otherwise. I think this should work now so do you think you could take care of the merge conflicts?

**Comment by xldenis** [comment]
Sure, otherwise I believe you can just overwrite them by running bless on the conflicting tests.

**Comment by xldenis** [comment]
Thank you @dewert99!
